services:
# Pastebin application
  web:
    build:
      context: Pastebin/src/.
      dockerfile: Pastebin.Web/Dockerfile
    ports: 
      - 4210:80
    depends_on:
      - identity-server
      - db
# PostgreSQL database server
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1+1is2
      POSTGRES_DB: PastebinDB
# PostgreSQL admin UI 
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
# Identity Server application
  identity-server:
    build:
      context: IdentityServer/.
      dockerfile: src/Dockerfile
    ports: 
      - 4205:80
# ui-react:
# ui-angular:
